[package]
name = "zktc-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.5.26", features = ["derive"] }
clap-num = "1.0.2"
nom = "7.1.3"
